### ISSUE TITLE
зауваження

### ISSUE THREAD

**Issue by OlgaKlekot** [Zlangobelz/EPAM-php-mentee#5]
-  посилання https://github.com/Zlangobelz/EPAM-php-mentee/blob/master/Arrays/task0.php#L98 мало б відображатися тільки після того як відбулося будь-яке фільтрування;

- тут: https://github.com/Zlangobelz/EPAM-php-mentee/blob/master/Arrays/task0.php#L75 і тут: https://github.com/Zlangobelz/EPAM-php-mentee/blob/master/Arrays/task0.php#L87 - чи будуть працювати посилання без "task0.php"?

- всі ціни маютьбути зі знаком "$"

**Comment by Zlangobelz** [comment]
відповідь на друге питання:
- Будуть. Для мене такий запис якось зрозуміліше. Звісно якшо назва файла не дуже довга і якшо вона не складається з якихось рандомних наборів букв
